-define(identity,0).
-define(reset,1).
-define(terminate,2).
-define(connect,3).
-define(getConstructors,4).
-define(lookupClass,5).
-define(getClassLocation,6).
-define(getMethods,7).
-define(getClasses,8).
-define(getFields,9).
-define(getConstructor,10).
-define(getMethod,11).
-define(getField,12).
-define(objTypeCompat,13).
-define(createThread,14).
-define(stopThread,15).
-define(free,16).
-define(freeInstance,17).
-define(memoryUsage,18).
-define(new_proxy_class,19).
-define(new_proxy_object,20).
-define(proxy_reply,21).

-define(last_nonthreaded_tag,21).

-define(call_method,51).
-define(call_constructor,52).
-define(getFieldValue,53).
-define(setFieldValue,54).
-define(getClassName,55).
-define(array_to_list,56).
-define(list_to_array,57).
-define(instof,58).
-define(convert,59).
-define(is_subtype,60).
-define(getSimpleClassName,61).

-define(last_tag,61).
